Repository cisagov/vulnrichment, pull requests merged in 2024-06, with the labels that each got.

#50 add citation and date
  assets/vulnrichment_big.dot
  assets/vulnrichment_big.dot.svg
Labels: documentation

#54 Update readme examples and link to CVE Services API
  README.md
Labels: documentation

#58 remove maybe references line
  README.md
Labels: documentation

#69 fix: correct affected versions in CVE-2023-32159
  2023/32xxx/CVE-2023-32159.json
Labels: bug, cpe

#57 Add a schema for the KEV entry under metrics
  assets/kev_metrics_schema-1.0.json
Labels: documentation, kev

#71 fix: correct affected versions in CVE-2024-4006
  2024/4xxx/CVE-2024-4006.json
Labels: bug, cpe

#72 fix: correct affected versions of gitlab release:2024-04-24
  2024/2xxx/CVE-2024-2434.json
  2024/2xxx/CVE-2024-2829.json
  2024/4xxx/CVE-2024-4024.json
Labels: bug, cpe
