Repository cisagov/vulnrichment, pull requests merged in 2024-05, with the labels that each got.

#7 tweak README, add CPE note
  README.md
Labels: documentation

#13 Fix version typo in CVE-2024-35184
  2024/35xxx/CVE-2024-35184.json
Labels: bug

#39 Update README.md wrt CVE updates
  README.md
Labels: documentation

#43 CISA ADP Version Using Integer Instead of String
  2024/30xxx/CVE-2024-30382.json
Labels: bug, cpe

#42 Inconsistency between adp.affected and cna.affected in CVE-2024-32761
  2024/32xxx/CVE-2024-32761.json
Labels: bug, cpe

#45 Update CVE-2024-32761.json
  2024/32xxx/CVE-2024-32761.json
Labels: bug

#44 add flowchart
  README.md
  assets/vulnrichment_big.dot
  assets/vulnrichment_big.dot.svg
Labels: documentation
