Repository cisagov/vulnrichment, pull requests merged in 2024-07, with the labels that each got.

#83 KEV schema doc pointer
  README.md
Labels: documentation, feature, kev

#79 fix typo in vulnrichment_big.dot
  assets/vulnrichment_big.dot
Labels: bug, documentation

#91 Add wording about SSVC version to the readme. Addresses #90
  README.md
Labels: documentation, ssvc
